require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRailsVersion: 6.1
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - Brewfile
    - 'bin/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Max: 23.28

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 14
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/conversation.rb'
    - 'app/models/user.rb'

Rails/HelperInstanceVariable:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - spec/features/**/*
    - spec/requests/**/*
    - spec/system/**/*

RSpec/ExampleLength:
  Max: 42

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RescueStandardError:
  Enabled: false
